server:
  port: 8761
# config bus
spring:
  rabbitmq:
    host: {HOST_IP} #config ip rabbitmq and for docker change the host for the ip of your machine
    port: 5672
    username: admin
    password: admin
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: {HOST_IP}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://actuator:password@${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
management:
  security:
    enabled: false    
